server:
  port: 10003

spring:
  application:
    name: mayor-of-city
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/mayor_of_city
  jpa:
    open-in-view: false

integration:
  production-of-numbers:
    url: http://localhost:10002

